ERROR 2024-04-28 22:32:37,585 django.request log log.py 241 log_response Internal Server Error: /mentee-signup
Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:5000/mentee-signup/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-04-28 22:32:37,588 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup HTTP/1.1" 500 74646
ERROR 2024-04-28 22:38:54,462 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
AssertionError: .accepted_renderer not set on Response
ERROR 2024-04-28 22:38:54,464 django.server basehttp basehttp.py 212 log_message "GET /mentee-signup/ HTTP/1.1" 500 73812
ERROR 2024-04-28 23:04:22,204 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\Growbinar_Backend\Authentication\views.py", line 11, in MenteeSignup
    first_name=request.data['firstName'],
               ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'firstName'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\http\response.py", line 134, in __init__
    self.status_code = int(status)
                       ^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\Growbinar_Backend\Authentication\views.py", line 31, in MenteeSignup
    return Response(500, {'message':'Error creating mentee'})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\response.py", line 30, in __init__
    super().__init__(None, status=status)
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\template\response.py", line 44, in __init__
    super().__init__("", content_type, status, charset=charset, headers=headers)
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\http\response.py", line 374, in __init__
    super().__init__(*args, **kwargs)
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\http\response.py", line 136, in __init__
    raise TypeError("HTTP status code must be an integer.")
TypeError: HTTP status code must be an integer.
ERROR 2024-04-28 23:04:22,207 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 129431
ERROR 2024-04-28 23:05:52,273 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:05:52,275 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 35
ERROR 2024-04-28 23:07:25,545 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
ERROR 2024-04-28 23:07:25,547 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 106058
ERROR 2024-04-28 23:08:00,674 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
ERROR 2024-04-28 23:08:00,676 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 106058
ERROR 2024-04-28 23:10:21,996 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\Growbinar_Backend\Authentication\views.py", line 12, in MenteeSignup
    first_name=request.data['firstName'],
               ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'firstName'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\growbinar code\Growbinar-Alpha-Backend\Growbinar_Backend\Authentication\views.py", line 32, in MenteeSignup
    return Response(json.dumps({'message':e}), status=500)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\91984\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
ERROR 2024-04-28 23:10:22,001 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 122869
ERROR 2024-04-28 23:11:38,226 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:11:38,227 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:12:21,940 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:12:21,942 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:12:51,584 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:12:51,585 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:13:20,682 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:13:20,683 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:14:09,991 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:14:09,992 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:14:34,423 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:14:34,424 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:14:52,417 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:14:52,418 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:15:44,512 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:15:44,514 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:17:42,199 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:17:42,200 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:19:37,886 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:19:37,887 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:26:48,425 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:26:48,427 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:27:48,059 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:27:48,061 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:28:59,659 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:28:59,660 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:29:19,652 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:29:19,652 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:32:02,033 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:32:02,036 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:41:15,565 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:41:15,567 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:42:11,433 django.request log log.py 241 log_response Internal Server Error: /mentee-signup/
ERROR 2024-04-28 23:42:11,434 django.server basehttp basehttp.py 212 log_message "POST /mentee-signup/ HTTP/1.1" 500 42
ERROR 2024-04-28 23:51:10,686 django.request log log.py 241 log_response Internal Server Error: /mentor-signup/
ERROR 2024-04-28 23:51:10,687 django.server basehttp basehttp.py 212 log_message "POST /mentor-signup/ HTTP/1.1" 500 42
